version: "3"
services:
  frontend:
    build:
      context: ./frontend
    command: ["nodemon", "index.js"]
    environment:
    - "NODE_ENV=development"
    - "DEBUG='express:*'"
    volumes:
    - ./frontend:/home/node/app
    restart: "no"

  backstopjs_worker_chrome:
    build:
      context: ./backstopjs_worker
      dockerfile: Dockerfile-chrome
    command: ["nodemon", "index.js"]
    environment:
    - "NODE_ENV=development"
    - "DEBUG='express:*'"
    volumes:
    - ./backstopjs_worker:/home/node/app
    restart: "no"

  backstopjs_worker_firefox:
    build:
      context: ./backstopjs_worker
      dockerfile: Dockerfile-firefox
    command: ["nodemon", "index.js"]
    environment:
      - "NODE_ENV=development"
      - "DEBUG='express:*'"
    volumes:
      - ./backstopjs_worker:/home/node/app
    restart: "no"

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - 'traefik.backend=portainer'
    - 'traefik.port=9000'
    - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'
    restart: "no"

  rabbitmq:
    restart: "no"

  traefik:
    restart: "no"