FROM node:10.16.3

ARG EXPOSED_PORT=10200

LABEL maintainer="mhavelant"

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "index.js"]

EXPOSE $EXPOSED_PORT

WORKDIR /home/node/app

HEALTHCHECK --interval=20s --timeout=3s --retries=3 \
    CMD node healthcheck.js

# @see: https://github.com/docksal/backstopjs/blob/master/Dockerfile
ENV PATH="/home/node/app/node_modules/.bin:${PATH}" \
	# Workaround to fix phantomjs-prebuilt installation errors
	# See https://github.com/Medium/phantomjs/issues/707
	NPM_CONFIG_UNSAFE_PERM=true \
	TINI_VERSION=v0.18.0 \
    EXPOSED_PORT=$EXPOSED_PORT \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    NODE_ENV=production

RUN \
    wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -O /sbin/tini && \
    chmod +x /sbin/tini && \
    apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates=20161130+nmu1+deb9u1 \
        software-properties-common=0.96.20.2-1 && \
    # Cleanupetc
    apt-get -y clean && \
    apt-get -y autoclean && \
    apt-get -y autoremove && \
    rm -rf \
        /var/lib/apt/lists/* \
        /var/cache/apt/* \
        /tmp/* \
        /var/tmp/* && \
    # Add these, so --no-sandbox is not needed for chrome.
    usermod -a -G audio,video node && \
    mkdir -p /home/node/Downloads && \
    mkdir -p /home/node/app/runtime/phantomjs && \
    chown -R node:node /home/node

USER node

COPY --chown=node package*.json ./

RUN npm ci --only=production && \
    npm cache -g clean --force

COPY --chown=node . .
