FROM node:10.7.0

LABEL maintainer="mhavelant"

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["xvfb-run", "-a", "npm", "start"]

EXPOSE 8080

WORKDIR /home/node/app

HEALTHCHECK --interval=20s --timeout=3s --retries=3 \
    CMD node healthcheck.js

# @see: https://github.com/docksal/backstopjs/blob/master/Dockerfile
ENV PATH="/home/node/app/node_modules/.bin:${PATH}" \
	DISPLAY=localhost:0.0 \
    MOZ_HEADLESS=1 \
	NPM_CONFIG_UNSAFE_PERM=true \
	FIREFOX_VERSION=52.9.0esr \
	TINI_VERSION=v0.18.0

RUN \
    wget "http://ftp.mozilla.org/pub/firefox/releases/${FIREFOX_VERSION}/linux-$(uname -m)/en-US/firefox-${FIREFOX_VERSION}.tar.bz2" && \
    tar -xjf firefox-${FIREFOX_VERSION}.tar.bz2 && \
    mv firefox /opt/ && \
    ln -s /opt/firefox/firefox /usr/bin/firefox && \
    # Tini.
    wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -O /sbin/tini && \
    chmod +x /sbin/tini

RUN \
    apt-get update && apt-get install -y --no-install-recommends \
        xvfb \
        xauth \
        libc6 \
        libstdc++6 \
        libgcc1 \
        libasound2 \
        libxrender1 \
        libdbus-glib-1-2 \
        libgtk-3-0 \
        libglib2.0 \
        libx11-xcb1 \
        libcogl-pango20 \
        dbus-x11 \
        ttf-freefont \
        fontconfig \
        ca-certificates \
        software-properties-common \
        python-software-properties && \
#        firefox-esr=${FIREFOX_ESR_VERSION} && \
    # Cleanupetc
    apt-get -y clean && \
    apt-get -y autoclean && \
    apt-get -y autoremove && \
    rm -rf \
        /var/lib/apt/lists/* \
        /var/cache/apt/* \
        /tmp/* \
        /var/tmp/*

COPY package*.json ./

RUN npm install --only=production && \
    # For some reason the new version does not work with slimer.
    npm install --save backstopjs@v3.0.26 && \
    npm cache -g clean --force && \
    usermod -a -G audio,video node && \
    mkdir -p /home/node/Downloads && \
    mkdir -p /home/node/app/runtime/firefox && \
    chown -R node:node /home/node

COPY . .

USER node
