FROM node:10.13.0

LABEL maintainer="mhavelant"

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["npm", "start"]

EXPOSE 10200

WORKDIR /home/node/app

HEALTHCHECK --interval=20s --timeout=3s --retries=3 \
    CMD node healthcheck.js

# @see: https://github.com/docksal/backstopjs/blob/master/Dockerfile
ENV PATH="/home/node/app/node_modules/.bin:${PATH}" \
	# Workaround to fix phantomjs-prebuilt installation errors
	# See https://github.com/Medium/phantomjs/issues/707
	NPM_CONFIG_UNSAFE_PERM=true \
	TINI_VERSION=v0.18.0 \
    EXPOSED_PORT=10200 \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

RUN \
    wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -O /sbin/tini && \
    chmod +x /sbin/tini && \
    apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        software-properties-common && \
    # Cleanupetc
    apt-get -y clean && \
    apt-get -y autoclean && \
    apt-get -y autoremove && \
    rm -rf \
        /var/lib/apt/lists/* \
        /var/cache/apt/* \
        /tmp/* \
        /var/tmp/*

COPY package*.json ./

RUN npm install --only=production && \
    npm cache -g clean --force && \
    usermod -a -G audio,video node && \
    mkdir -p /home/node/Downloads && \
    mkdir -p /home/node/app/runtime/phantomjs && \
    chown -R node:node /home/node

COPY . .

USER node
