FROM node:10.15.1

LABEL maintainer="mhavelant"

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["npm", "start"]

EXPOSE 10000

WORKDIR /home/node/app

HEALTHCHECK --interval=20s --timeout=3s --retries=3 \
    CMD node healthcheck.js

# @see: https://github.com/docksal/backstopjs/blob/master/Dockerfile
ENV PATH="/home/node/app/node_modules/.bin:${PATH}" \
	# Workaround to fix phantomjs-prebuilt installation errors
	# See https://github.com/Medium/phantomjs/issues/707
	NPM_CONFIG_UNSAFE_PERM=true \
	TINI_VERSION=v0.18.0 \
    EXPOSED_PORT=10000

# Base packages
RUN wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -O /sbin/tini && \
    chmod +x /sbin/tini && \
    apt-get update && \
    wget https://dl-ssl.google.com/linux/linux_signing_key.pub && \
    apt-key add linux_signing_key.pub && \
    apt-get install -y --no-install-recommends \
        software-properties-common=0.96.20.2-1 && \
    add-apt-repository "deb http://dl.google.com/linux/chrome/deb/ stable main" && \
    apt-get update && \
	apt-get install -y --no-install-recommends \
#	    google-chrome-stable=72.0.3626.96-1 \
	    google-chrome-stable=70.0.3538.110-1 \
	    fonts-ipafont-gothic=00303-16 \
	    fonts-wqy-zenhei=0.9.45-6 \
	    fonts-thai-tlwg=1:0.6.3-1 \
	    fonts-kacst=2.01+mry-12 \
	    ttf-freefont=20120503-6 && \
    # Cleanupetc
    apt-get -y clean && \
    apt-get -y autoclean && \
    apt-get -y autoremove && \
    rm -rf \
        /var/lib/apt/lists/* \
        /var/cache/apt/* \
        /tmp/* \
        /var/tmp/*

COPY package*.json ./

RUN npm install --only=production && \
    npm cache -g clean --force && \
    # Add these, so --no-sandbox is not needed for chrome.
    usermod -a -G audio,video node && \
    mkdir -p /home/node/Downloads && \
    mkdir -p /home/node/app/runtime/chrome && \
    chown -R node:node /home/node

COPY . .

ENV NODE_ENV=production

USER node

